name: Front2End
description: 'Share front end technology, improve user experience'
meta_description: 'front2end'
permalink: /:year/:month/:day/:title
avatar: '/assets/img/front2end.jpg'
gems: [jekyll-paginate]
markdown: kramdown
logo: '/assets/img/front2end.jpg'
paginate: 6
baseurl: /
domain_name: 'http://front2end.com'
google_analytics: 'UA-XXXXXXXX-X'
url:            'http://front2end.com'
author:         'Front2End'
